services:
  database:
    container_name: clone-tabnews
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5454:5432"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025" #server smpt
      - "1080:1080" #UI
